eureka:
  client:
    serviceUrl:
#      eureka.client.serviceUrl.defaultZone 的作用是指定注册中心的地址。
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8772
spring:
  application:
    name: eurekaclient